CREATE TABLE IF NOT EXISTS KEY_KANJI (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    SYMBOL_KEY CHAR(1) NOT NULL,
    NAME_KEY VARCHAR(40) NOT NULL,
    STROKES TINYINT NOT NULL,
    KEY_NUMBER SMALLINT NOT NULL,
    PRIMARY KEY(ID)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS KANJI (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    SYMBOL CHAR(1) NOT NULL,
    STROKES TINYINT NOT NULL,
    PRIMARY KEY(ID)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS READINGS_ON (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    READING_ON VARCHAR(100) NOT NULL,
    ID_KANJI BIGINT NOT NULL,
    FOREIGN KEY(ID_KANJI) REFERENCES KANJI(ID),
    PRIMARY KEY(ID)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS READINGS_KUN (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    READING_KUN VARCHAR(100) NOT NULL,
    ID_KANJI BIGINT NOT NULL,
    FOREIGN KEY(ID_KANJI) REFERENCES KANJI(ID),
    PRIMARY KEY(ID)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS MEANINGS_FR (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    MEANING_FR VARCHAR(100) NOT NULL,
    ID_KANJI BIGINT NOT NULL,
    FOREIGN KEY(ID_KANJI) REFERENCES KANJI(ID),
    PRIMARY KEY(ID)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS KANJI_KEY_KANJI(
    ID_KANJI BIGINT NOT NULL,
    ID_KEY_KANJI BIGINT NOT NULL,
    PRIMARY KEY (ID_KANJI,ID_KEY_KANJI),
    FOREIGN KEY(ID_KANJI) REFERENCES KANJI(ID),
    FOREIGN KEY(ID_KEY_KANJI) REFERENCES KEY_KANJI(ID)
    ) ENGINE=InnoDB;